name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Executa ao fazer push de tags que começam com "v"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: token_geral 
        TWINE_PASSWORD: ${{ secrets.pypi-AgEIcHlwaS5vcmcCJDFiOThlMjIzLWJjZWItNDRmYi1hZmUwLWRmYzg5ZWQ5ZDY0ZAACKlszLCI5YTViZDVlYy1lZTAwLTQyYjAtODJiZS1kZjM0MzZjMjBmNWMiXQAABiB7z2cixFTjIripP1akaB0BPyXmapv69BDPhnKRBBrE_w }} 
      run: twine upload dist/*
